# Generated by Django 3.1.2 on 2020-10-31 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('projector', 'projector'), ('tv', 'tv'), ('whiteboard', 'whiteboard'), ('speakers', 'speakers'), ('phone', 'phone'), ('air_conditioning', 'air conditioning')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('maximum_occupancy', models.PositiveIntegerField()),
                ('cost_per_hour', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Time of deletion')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='appointments.meetingroom')),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
