# Generated by Django 3.1.2 on 2020-11-01 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('projector', 'projector'), ('tv', 'tv'), ('whiteboard', 'whiteboard'), ('speakers', 'speakers'), ('phone', 'phone'), ('air_conditioning', 'air conditioning')], max_length=32, unique=True)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Time of deletion')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('maximum_occupancy', models.PositiveIntegerField()),
                ('cost_per_hour', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment_Participant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Time of deletion')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('appointment', 'user')},
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='appointments.meetingroom'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='participants',
            field=models.ManyToManyField(blank=True, through='appointments.Appointment_Participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
