# Generated by Django 3.1.2 on 2020-11-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterField(
            model_name='appointment_participant',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Time of participant deletion'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment_participant',
            unique_together=set(),
        ),
    ]
