# Generated by Django 3.1.2 on 2020-10-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='meetingroom',
            old_name='_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='amenity',
            name='description',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
