# Generated by Django 3.1.2 on 2020-11-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20201101_1751'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('location', 'start_time', 'end_time')},
        ),
    ]
