# Generated by Django 3.1.2 on 2020-11-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20201101_1757'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('start_time', 'end_time')},
        ),
    ]
