# Generated by Django 3.1.2 on 2020-11-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20201101_1855'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment_participant',
            constraint=models.UniqueConstraint(fields=('appointment', 'user'), name='unique appversion'),
        ),
    ]
