# Generated by Django 3.1.2 on 2020-11-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20201102_0220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
